apiVersion: s3.aws.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: argocd-bucket
spec:
  forProvider:
    acl: private
    locationConstraint: eu-west-3
  providerConfigRef:
    name: aws-provider
